apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy 
spec:
  steps:   
    - name: oc-binary-build 
      image: quay.io/openshift-pipeline/openshift-cli:latest
      command: ["/usr/local/bin/oc"]
      args:
        - rollout 
        - latest
        - todolist 
