apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: todolist
      template: todolist-build-template
    name: todolist
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: todolist:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
  status:
    lastVersion: 1
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: todolist
      template: todolist-build-template
    name: todolist
  spec: {}
kind: List
metadata: {}
