apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: todolist
      template: todolist-deploy-template
    name: todolist
  spec:
    replicas: 1
    selector:
      name: todolist
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: todolist
      spec:
        containers:
        - env:
          - name: NODE_ENV
            value: dev
          image: image-registry.openshift-image-registry.svc:5000/summit-tekton/todolist:latest
          imagePullPolicy: Always
          name: todolist
          ports:
          - containerPort: 9000
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: todolist
      template: todolist-deploy-template
    name: todolist
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      name: todolist
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      name: todolist
      template: todolist-deploy-template
    name: todolist
  spec:
    port:
      targetPort: 9000-tcp
    to:
      kind: Service
      name: todolist
      weight: 100
    wildcardPolicy: None
kind: List
metadata: {}
